# Set theme
theme: alembic-jekyll-theme
# 
exclude:
-
 _redirects
# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock
# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
# defaults
defaults:
  -
    scope:
      path: ""		
      type: "facebook"
    values:
    layout: "fb"
    permalink: /:path/
  -
    scope:
      path: ""
      type: "link2app"
    values:
        layout: "link2app"
    permalink: /:path/
      -
    scope:
      path: ""
      type: "oiin-cofigs"
    values:
        layout: "oiin-layout"
    permalink: /:path/
    #
    collections:
    facebook:
    output: true 
# Site settings
title: 'shares'
description: 'Shares Android apps & Tutorials'
baseurl: ''
url: 'https://shares.netlify.com'
# permalink: pretty
logo: "https://shares.netlify.com/img/androids.png"
#     # 
baseurl: ''
compress_html:
  clippings: all
  comments: all
  endings: all
  ignore:
    envs: [local]
  blanklines: false
  startings: [html, head, body] 
