theme: alembic-jekyll-theme 
exclude:
-
 _redirects
exclude:
- README.md
- Gemfile
- Gemfile.lock
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
collections:
facebook:
 output: true
link2app:
 output: true
oiin-cofigs:
 output: true
title: 'shares'
description: 'Shares Android apps & Tutorials'
baseurl: ''
logo: "https://shares.netlify.com/img/androids.png"
baseurl: ''
compress_html:
  clippings: all
  comments: all
  endings: all
  ignore:
    envs: [local]
  blanklines: false
  startings: [html, head, body] 
